import {PlayCricketMatchDetail, team} from "@navestockcricketclub-monorepo-v2/interface-playcricket"
import {Match} from "@navestockcricketclub-monorepo-v2/interfaces-match"
import { Timestamp } from "firebase-admin/firestore";


/**
 * Playcricket Match Detailed mock data as it would be returned byt the Playcricket API
 */
export const PlayCricketMatchDetail_TestData: PlayCricketMatchDetail[] = [
    {
      id: 5270849,
      status: 'New',
      published: 'Yes',
      last_updated: '08/09/2022',
      league_name: 'Mid Essex Cricket League',
      league_id: '400',
      competition_name: 'Third Division',
      competition_id: '103838',
      competition_type: 'League',
      match_type: 'Limited Overs',
      game_type: 'Standard',
      countdown_cricket: 'no',
      match_id: '5270849',
      match_date: '03/09/2022',
      match_time: '13:00',
      ground_name: 'Rawreth Lane (new ground)',
      ground_id: '9345',
      home_team_name: '2nd XI',
      home_team_id: '22338',
      home_club_name: 'Rayleigh CC',
      home_club_id: '5276',
      away_team_name: '1st XI',
      away_team_id: '204935',
      away_club_name: 'Navestock CC',
      away_club_id: '4513',
      umpire_1_name: '',
      umpire_1_id: '',
      umpire_2_name: '',
      umpire_2_id: '',
      umpire_3_name: '',
      umpire_3_id: '',
      referee_name: '',
      referee_id: '',
      scorer_1_name: '',
      scorer_1_id: '',
      scorer_2_name: '',
      scorer_2_id: '',
      toss_won_by_team_id: '204935',
      toss: 'Navestock CC - 1st XI won the toss and elected to bat',
      batted_first: '204935',
      no_of_overs: '45',
      balls_per_innings: '',
      no_of_innings: '1',
      no_of_days: '1',
      no_of_players: '',
      no_of_reserves: '',
      result: 'W',
      result_description: 'Rayleigh CC - 2nd XI - win',
      result_applied_to: '22338',
      match_notes:
        '<p>Tom Greaves 109, Ross Glumart 90, Phil Sergeant 34, Matt Gates 3-17, Jack Gildersleeve 2-1, Nilesh Patel 2-9, Steve Gawler 2-20 (NCC) - Ant Larcher 2-55, Anil Kumar 30 (SJBCC) </p>',
      points: [
        {
          team_id: 22338,
          game_points: '16',
          penalty_points: '',
          bonus_points_together: '7.0',
          bonus_points_batting: '4.0',
          bonus_points_bowling: '3.0',
          bonus_points_2nd_innings_together: '',
        },
        {
          team_id: 204935,
          game_points: '0',
          penalty_points: '',
          bonus_points_together: '5.0',
          bonus_points_batting: '4.0',
          bonus_points_bowling: '1.0',
          bonus_points_2nd_innings_together: '',
        },
      ],
      match_result_types: [
        ['Rayleigh CC - 2nd XI - win', '857718#22338'],
        ['Navestock CC - 1st XI - win', '857718#204935'],
        ['Rayleigh CC - 2nd XI - win forfeit', '857720#22338'],
        ['Navestock CC - 1st XI - win forfeit', '857720#204935'],
        ['Tied', 833863],
        ['Cancelled', 833859],
        ['Abandoned', 833860],
        ['Match In Progress', 14],
      ],
      players: [
        {
          home_team: [
            {
              position: 1,
              player_name: 'James Ellis',
              player_id: 614028,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 2,
              player_name: 'Christopher Henderson',
              player_id: 5400727,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 3,
              player_name: 'Mark Acraman',
              player_id: 4353624,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 4,
              player_name: 'Sam Harmsworth',
              player_id: 5010596,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 5,
              player_name: 'Matthew Walker',
              player_id: 6188,
              captain: true,
              wicket_keeper: false,
            },
            {
              position: 6,
              player_name: 'Steven Lynch',
              player_id: 741512,
              captain: false,
              wicket_keeper: true,
            },
            {
              position: 7,
              player_name: 'Calum Mayfield',
              player_id: 5371998,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 8,
              player_name: 'Aaron Mayfield',
              player_id: 4114658,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 9,
              player_name: 'Mihir Patel',
              player_id: 3626541,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 10,
              player_name: 'Nick Green',
              player_id: 977636,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 11,
              player_name: 'Trevor Nunn',
              player_id: 5505062,
              captain: false,
              wicket_keeper: false,
            },
          ],
        },
        {
          away_team: [
            {
              position: 1,
              player_name: 'Jonathan Enderby',
              player_id: 3902682,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 2,
              player_name: 'Tom Greaves',
              player_id: 2568570,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 3,
              player_name: 'Kieron Scott',
              player_id: 3789286,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 4,
              player_name: 'Malcolm Goddard',
              player_id: 4927327,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 5,
              player_name: 'Liam Faulkner',
              player_id: 3691460,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 6,
              player_name: 'Matthew Richards',
              player_id: 3755520,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 7,
              player_name: 'Imran Munir',
              player_id: 5064741,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 8,
              player_name: 'Tom Mccarthy',
              player_id: 3974661,
              captain: false,
              wicket_keeper: false,
            },
            {
              position: 9,
              player_name: 'Billy Greaves',
              player_id: 3757848,
              captain: true,
              wicket_keeper: false,
            },
            {
              position: 10,
              player_name: 'Ryan Scott',
              player_id: 3757849,
              captain: false,
              wicket_keeper: false,
            },
          ],
        },
      ],
      innings: [
        {
          team_batting_name: 'Navestock CC - 1st XI',
          team_batting_id: '204935',
          innings_number: 1,
          extra_byes: '11',
          extra_leg_byes: '7',
          extra_wides: '3',
          extra_no_balls: '3',
          extra_penalty_runs: '0',
          penalties_runs_awarded_in_other_innings: '',
          total_extras: '24',
          runs: '213',
          wickets: '7',
          overs: '45',
          balls: '',
          declared: false,
          forfeited_innings: false,
          revised_target_runs: '',
          revised_target_overs: '45.0',
          revised_target_balls: '',
          bat: [
            {
              position: '1',
              batsman_name: 'Jonathan Enderby',
              batsman_id: '3902682',
              how_out: 'run out',
              fielder_name: 'Nick Green',
              fielder_id: '977636',
              bowler_name: '',
              bowler_id: '',
              runs: '65',
              fours: '12',
              sixes: '',
              balls: '',
            },
            {
              position: '2',
              batsman_name: 'Tom Greaves',
              batsman_id: '2568570',
              how_out: 'ct',
              fielder_name: 'Trevor Nunn',
              fielder_id: '5505062',
              bowler_name: 'Nick Green',
              bowler_id: '977636',
              runs: '14',
              fours: '2',
              sixes: '',
              balls: '',
            },
            {
              position: '3',
              batsman_name: 'Kieron Scott',
              batsman_id: '3789286',
              how_out: 'ct',
              fielder_name: 'Trevor Nunn',
              fielder_id: '5505062',
              bowler_name: 'Calum Mayfield',
              bowler_id: '5371998',
              runs: '37',
              fours: '6',
              sixes: '',
              balls: '',
            },
            {
              position: '4',
              batsman_name: 'Malcolm Goddard',
              batsman_id: '4927327',
              how_out: 'b',
              fielder_name: '',
              fielder_id: '',
              bowler_name: 'Mihir Patel',
              bowler_id: '3626541',
              runs: '10',
              fours: '1',
              sixes: '',
              balls: '',
            },
            {
              position: '5',
              batsman_name: 'Liam Faulkner',
              batsman_id: '3691460',
              how_out: 'not out',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '30',
              fours: '5',
              sixes: '',
              balls: '',
            },
            {
              position: '6',
              batsman_name: 'Matthew Richards',
              batsman_id: '3755520',
              how_out: 'b',
              fielder_name: '',
              fielder_id: '',
              bowler_name: 'Trevor Nunn',
              bowler_id: '5505062',
              runs: '10',
              fours: '',
              sixes: '',
              balls: '',
            },
            {
              position: '7',
              batsman_name: 'Imran Munir',
              batsman_id: '5064741',
              how_out: 'ct',
              fielder_name: 'Sam Harmsworth',
              fielder_id: '5010596',
              bowler_name: 'Aaron Mayfield',
              bowler_id: '4114658',
              runs: '19',
              fours: '1',
              sixes: '1',
              balls: '',
            },
            {
              position: '8',
              batsman_name: 'Tom Mccarthy',
              batsman_id: '3974661',
              how_out: 'ct',
              fielder_name: 'Calum Mayfield',
              fielder_id: '5371998',
              bowler_name: 'Trevor Nunn',
              bowler_id: '5505062',
              runs: '2',
              fours: '',
              sixes: '',
              balls: '',
            },
            {
              position: '9',
              batsman_name: 'Billy Greaves',
              batsman_id: '3757848',
              how_out: 'not out',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '2',
              fours: '',
              sixes: '',
              balls: '',
            },
            {
              position: '10',
              batsman_name: 'Ryan Scott',
              batsman_id: '3757849',
              how_out: 'did not bat',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '',
              fours: '',
              sixes: '',
              balls: '',
            },
          ],
          fow: [
            {
              runs: '42',
              wickets: 1,
              batsman_out_name: 'Tom Greaves',
              batsman_out_id: '2568570',
              batsman_in_name: 'Jonathan Enderby',
              batsman_in_id: '3902682',
              batsman_in_runs: '',
            },
            {
              runs: '106',
              wickets: 2,
              batsman_out_name: 'Jonathan Enderby',
              batsman_out_id: '3902682',
              batsman_in_name: 'Kieron Scott',
              batsman_in_id: '3789286',
              batsman_in_runs: '',
            },
            {
              runs: '142',
              wickets: 3,
              batsman_out_name: 'Malcolm Goddard',
              batsman_out_id: '4927327',
              batsman_in_name: 'Kieron Scott',
              batsman_in_id: '3789286',
              batsman_in_runs: '',
            },
            {
              runs: '142',
              wickets: 4,
              batsman_out_name: 'Kieron Scott',
              batsman_out_id: '3789286',
              batsman_in_name: 'Liam Faulkner',
              batsman_in_id: '3691460',
              batsman_in_runs: '',
            },
            {
              runs: '179',
              wickets: 5,
              batsman_out_name: 'Matthew Richards',
              batsman_out_id: '3755520',
              batsman_in_name: 'Liam Faulkner',
              batsman_in_id: '3691460',
              batsman_in_runs: '',
            },
            {
              runs: '208',
              wickets: 6,
              batsman_out_name: 'Imran Munir',
              batsman_out_id: '5064741',
              batsman_in_name: 'Liam Faulkner',
              batsman_in_id: '3691460',
              batsman_in_runs: '',
            },
            {
              runs: '210',
              wickets: 7,
              batsman_out_name: 'Tom Mccarthy',
              batsman_out_id: '3974661',
              batsman_in_name: 'Liam Faulkner',
              batsman_in_id: '3691460',
              batsman_in_runs: '',
            },
          ],
          bowl: [
            {
              bowler_name: 'Trevor Nunn',
              bowler_id: '5505062',
              overs: '9',
              maidens: '0',
              runs: '51',
              wides: '0',
              wickets: '2',
              no_balls: '0',
            },
            {
              bowler_name: 'Calum Mayfield',
              bowler_id: '5371998',
              overs: '9',
              maidens: '0',
              runs: '31',
              wides: '0',
              wickets: '1',
              no_balls: '0',
            },
            {
              bowler_name: 'Aaron Mayfield',
              bowler_id: '4114658',
              overs: '9',
              maidens: '1',
              runs: '43',
              wides: '0',
              wickets: '1',
              no_balls: '0',
            },
            {
              bowler_name: 'Nick Green',
              bowler_id: '977636',
              overs: '9',
              maidens: '2',
              runs: '34',
              wides: '0',
              wickets: '1',
              no_balls: '0',
            },
            {
              bowler_name: 'Mihir Patel',
              bowler_id: '3626541',
              overs: '9',
              maidens: '1',
              runs: '36',
              wides: '0',
              wickets: '1',
              no_balls: '0',
            },
          ],
        },
        {
          team_batting_name: 'Rayleigh CC - 2nd XI',
          team_batting_id: '22338',
          innings_number: 1,
          extra_byes: '4',
          extra_leg_byes: '4',
          extra_wides: '3',
          extra_no_balls: '1',
          extra_penalty_runs: '0',
          penalties_runs_awarded_in_other_innings: '',
          total_extras: '12',
          runs: '215',
          wickets: '2',
          overs: '26',
          balls: '',
          declared: false,
          forfeited_innings: false,
          revised_target_runs: '',
          revised_target_overs: '45.0',
          revised_target_balls: '',
          bat: [
            {
              position: '1',
              batsman_name: 'James Ellis',
              batsman_id: '614028',
              how_out: 'not out',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '112',
              fours: '12',
              sixes: '5',
              balls: '76',
            },
            {
              position: '2',
              batsman_name: 'Christopher Henderson',
              batsman_id: '5400727',
              how_out: 'ct',
              fielder_name: 'Imran Munir',
              fielder_id: '5064741',
              bowler_name: 'Billy Greaves',
              bowler_id: '3757848',
              runs: '74',
              fours: '14',
              sixes: '1',
              balls: '70',
            },
            {
              position: '3',
              batsman_name: 'Mark Acraman',
              batsman_id: '4353624',
              how_out: 'ct',
              fielder_name: 'Ryan Scott',
              fielder_id: '3757849',
              bowler_name: 'Billy Greaves',
              bowler_id: '3757848',
              runs: '12',
              fours: '2',
              sixes: '',
              balls: '10',
            },
            {
              position: '4',
              batsman_name: 'Sam Harmsworth',
              batsman_id: '5010596',
              how_out: 'not out',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '5',
              fours: '1',
              sixes: '',
              balls: '4',
            },
            {
              position: '5',
              batsman_name: 'Matthew Walker',
              batsman_id: '6188',
              how_out: 'did not bat',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '',
              fours: '',
              sixes: '',
              balls: '',
            },
            {
              position: '6',
              batsman_name: 'Steven Lynch',
              batsman_id: '741512',
              how_out: 'did not bat',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '',
              fours: '',
              sixes: '',
              balls: '',
            },
            {
              position: '7',
              batsman_name: 'Calum Mayfield',
              batsman_id: '5371998',
              how_out: 'did not bat',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '',
              fours: '',
              sixes: '',
              balls: '',
            },
            {
              position: '8',
              batsman_name: 'Aaron Mayfield',
              batsman_id: '4114658',
              how_out: 'did not bat',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '',
              fours: '',
              sixes: '',
              balls: '',
            },
            {
              position: '9',
              batsman_name: 'Mihir Patel',
              batsman_id: '3626541',
              how_out: 'did not bat',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '',
              fours: '',
              sixes: '',
              balls: '',
            },
            {
              position: '10',
              batsman_name: 'Nick Green',
              batsman_id: '977636',
              how_out: 'did not bat',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '',
              fours: '',
              sixes: '',
              balls: '',
            },
            {
              position: '11',
              batsman_name: 'Trevor Nunn',
              batsman_id: '5505062',
              how_out: 'did not bat',
              fielder_name: '',
              fielder_id: '',
              bowler_name: '',
              bowler_id: '',
              runs: '',
              fours: '',
              sixes: '',
              balls: '',
            },
          ],
          fow: [
            {
              runs: '178',
              wickets: 1,
              batsman_out_name: 'Christopher Henderson',
              batsman_out_id: '5400727',
              batsman_in_name: 'James Ellis',
              batsman_in_id: '614028',
              batsman_in_runs: '91',
            },
            {
              runs: '199',
              wickets: 2,
              batsman_out_name: 'Mark Acraman',
              batsman_out_id: '4353624',
              batsman_in_name: 'James Ellis',
              batsman_in_id: '614028',
              batsman_in_runs: '102',
            },
          ],
          bowl: [
            {
              bowler_name: 'Tom Mccarthy',
              bowler_id: '3974661',
              overs: '5',
              maidens: '1',
              runs: '39',
              wides: '0',
              wickets: '0',
              no_balls: '0',
            },
            {
              bowler_name: 'Billy Greaves',
              bowler_id: '3757848',
              overs: '6',
              maidens: '0',
              runs: '48',
              wides: '0',
              wickets: '2',
              no_balls: '0',
            },
            {
              bowler_name: 'Ryan Scott',
              bowler_id: '3757849',
              overs: '6',
              maidens: '0',
              runs: '70',
              wides: '0',
              wickets: '0',
              no_balls: '0',
            },
            {
              bowler_name: 'Imran Munir',
              bowler_id: '5064741',
              overs: '6',
              maidens: '1',
              runs: '23',
              wides: '0',
              wickets: '0',
              no_balls: '0',
            },
            {
              bowler_name: 'Liam Faulkner',
              bowler_id: '3691460',
              overs: '3',
              maidens: '0',
              runs: '27',
              wides: '0',
              wickets: '0',
              no_balls: '0',
            },
          ],
        },
      ],
    },
  ];


/**
 * Match Detail mock data after data transformation 
 */  
export const MatchDetail_TestResultData: Match[] = [
    {
      description: {
        id: 5270849,
        status: 'New',
        published: 'Yes',
        last_updated: '08/09/2022',
        last_updated_timestamp: Timestamp.fromMillis(1662634800000),
        league_name: 'Mid Essex Cricket League',
        league_id: '400',
        competition_name: 'Third Division',
        competition_id: '103838',
        competition_type: 'League',
        match_type: 'Limited Overs',
        game_type: 'Standard',
        countdown_cricket: 'no',
        match_id: '5270849',
        match_date: '03/09/2022',
        match_time: '13:00',
        match_date_timestamp: Timestamp.fromMillis(1662206400000),
        ground_name: 'Rawreth Lane (new ground)',
        ground_id: '9345',
        home_team_name: '2nd XI',
        home_team_id: '22338',
        home_club_name: 'Rayleigh CC',
        home_club_id: '5276',
        away_team_name: '1st XI',
        away_team_id: '204935',
        away_club_name: 'Navestock CC',
        away_club_id: '4513',
        home_team_isNavestock: false,
        navestock_club_name: 'Navestock CC',
        navestock_team_name: '1st XI',
        navestock_team_id: '204935',
        navestock_club_id: '4513',
        opposition_club_name: 'Rayleigh CC',
        opposition_team_name: '2nd XI',
        opposition_team_id: '22338',
        opposition_club_id: '5276',
        toss_won_by_team_id: '204935',
        toss: 'Navestock CC - 1st XI won the toss and elected to bat',
        batted_first: '204935',
        no_of_overs: '45',
        no_of_innings: '1',
        no_of_days: '1',
        result: 'W',
        result_description: 'Rayleigh CC - 2nd XI - win',
        result_applied_to: '22338',
        match_notes:
          'Tom Greaves 109, Ross Glumart 90, Phil Sergeant 34, Matt Gates 3-17, Jack Gildersleeve 2-1, Nilesh Patel 2-9, Steve Gawler 2-20 (NCC) - Ant Larcher 2-55, Anil Kumar 30 (SJBCC) ',
      },
      innings: [
        {
          description: {
            club_batting_id: '4513',
            club_batting_name: 'Navestock CC',
            club_bowling_id: '5276',
            club_bowling_name: 'Rayleigh CC',
            declared: false,
            extra_byes: 11,
            extra_leg_byes: 7,
            extra_no_balls: 3,
            extra_penalty_runs: 0,
            extra_wides: 3,
            forfeited_innings: false,
            innings_number: 1,
            match_id: 5270849,
            overs: 45,
            revised_target_overs: 45,
            runs: 213,
            team_batting_id: '204935',
            team_batting_name: '1st XI',
            team_bowling_id: '22338',
            team_bowling_name: '2nd XI',
            total_extras: 24,
            wickets: 7,
          },
          bat: [
            {
              position: 1,
              batsman_name: 'Jonathan Enderby',
              batsman_id: '3902682',
              how_out: 'run out',
              fielder_name: 'Nick Green',
              fielder_id: '977636',
              runs: 65,
              fours: 12,
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              position: 2,
              batsman_name: 'Tom Greaves',
              batsman_id: '2568570',
              how_out: 'ct',
              fielder_name: 'Trevor Nunn',
              fielder_id: '5505062',
              bowler_name: 'Nick Green',
              bowler_id: '977636',
              runs: 14,
              fours: 2,
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              position: 3,
              batsman_name: 'Kieron Scott',
              batsman_id: '3789286',
              how_out: 'ct',
              fielder_name: 'Trevor Nunn',
              fielder_id: '5505062',
              bowler_name: 'Calum Mayfield',
              bowler_id: '5371998',
              runs: 37,
              fours: 6,
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              position: 4,
              batsman_name: 'Malcolm Goddard',
              batsman_id: '4927327',
              how_out: 'b',
              bowler_name: 'Mihir Patel',
              bowler_id: '3626541',
              runs: 10,
              fours: 1,
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              position: 5,
              batsman_name: 'Liam Faulkner',
              batsman_id: '3691460',
              how_out: 'not out',
              runs: 30,
              fours: 5,
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              position: 6,
              batsman_name: 'Matthew Richards',
              batsman_id: '3755520',
              how_out: 'b',
              bowler_name: 'Trevor Nunn',
              bowler_id: '5505062',
              runs: 10,
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              position: 7,
              batsman_name: 'Imran Munir',
              batsman_id: '5064741',
              how_out: 'ct',
              fielder_name: 'Sam Harmsworth',
              fielder_id: '5010596',
              bowler_name: 'Aaron Mayfield',
              bowler_id: '4114658',
              runs: 19,
              fours: 1,
              sixes: 1,
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              position: 8,
              batsman_name: 'Tom Mccarthy',
              batsman_id: '3974661',
              how_out: 'ct',
              fielder_name: 'Calum Mayfield',
              fielder_id: '5371998',
              bowler_name: 'Trevor Nunn',
              bowler_id: '5505062',
              runs: 2,
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              position: 9,
              batsman_name: 'Billy Greaves',
              batsman_id: '3757848',
              how_out: 'not out',
              runs: 2,
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              position: 10,
              batsman_name: 'Ryan Scott',
              batsman_id: '3757849',
              how_out: 'did not bat',
              club_id: '4513',
              club_name: 'Navestock CC',
              team_id: '204935',
              team_name: '1st XI',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
          ],
          bowl: [
            {
              bowler_id: '5505062',
              bowler_name: 'Trevor Nunn',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              club_id: '4513',
              club_name: 'Navestock CC',
              maidens: 0,
              match_id: 5270849,
              no_balls: 0,
              overs: 9,
              runs: 51,
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              team_id: '204935',
              team_name: '1st XI',
              wickets: 2,
              wides: 0,
            },
            {
              bowler_id: '5371998',
              bowler_name: 'Calum Mayfield',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              club_id: '4513',
              club_name: 'Navestock CC',
              maidens: 0,
              match_id: 5270849,
              no_balls: 0,
              overs: 9,
              runs: 31,
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              team_id: '204935',
              team_name: '1st XI',
              wickets: 1,
              wides: 0,
            },
            {
              bowler_id: '4114658',
              bowler_name: 'Aaron Mayfield',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              club_id: '4513',
              club_name: 'Navestock CC',
              maidens: 1,
              match_id: 5270849,
              no_balls: 0,
              overs: 9,
              runs: 43,
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              team_id: '204935',
              team_name: '1st XI',
              wickets: 1,
              wides: 0,
            },
            {
              bowler_id: '977636',
              bowler_name: 'Nick Green',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              club_id: '4513',
              club_name: 'Navestock CC',
              maidens: 2,
              match_id: 5270849,
              no_balls: 0,
              overs: 9,
              runs: 34,
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              team_id: '204935',
              team_name: '1st XI',
              wickets: 1,
              wides: 0,
            },
            {
              bowler_id: '3626541',
              bowler_name: 'Mihir Patel',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              club_id: '4513',
              club_name: 'Navestock CC',
              maidens: 1,
              match_id: 5270849,
              no_balls: 0,
              overs: 9,
              runs: 36,
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              team_id: '204935',
              team_name: '1st XI',
              wickets: 1,
              wides: 0,
            },
          ],
          fow: [
            {
              runs: 42,
              wickets: 1,
              batsman_out_name: 'Tom Greaves',
              batsman_out_id: '2568570',
              batsman_in_name: 'Jonathan Enderby',
              batsman_in_id: '3902682',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              runs: 106,
              wickets: 2,
              batsman_out_name: 'Jonathan Enderby',
              batsman_out_id: '3902682',
              batsman_in_name: 'Kieron Scott',
              batsman_in_id: '3789286',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              runs: 142,
              wickets: 3,
              batsman_out_name: 'Malcolm Goddard',
              batsman_out_id: '4927327',
              batsman_in_name: 'Kieron Scott',
              batsman_in_id: '3789286',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              runs: 142,
              wickets: 4,
              batsman_out_name: 'Kieron Scott',
              batsman_out_id: '3789286',
              batsman_in_name: 'Liam Faulkner',
              batsman_in_id: '3691460',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              runs: 179,
              wickets: 5,
              batsman_out_name: 'Matthew Richards',
              batsman_out_id: '3755520',
              batsman_in_name: 'Liam Faulkner',
              batsman_in_id: '3691460',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              runs: 208,
              wickets: 6,
              batsman_out_name: 'Imran Munir',
              batsman_out_id: '5064741',
              batsman_in_name: 'Liam Faulkner',
              batsman_in_id: '3691460',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
            {
              runs: 210,
              wickets: 7,
              batsman_out_name: 'Tom Mccarthy',
              batsman_out_id: '3974661',
              batsman_in_name: 'Liam Faulkner',
              batsman_in_id: '3691460',
              team_batting_id: '204935',
              team_batting_name: '1st XI',
              club_batting_id: '4513',
              club_batting_name: 'Navestock CC',
              club_bowling_id: '5276',
              club_bowling_name: 'Rayleigh CC',
              team_bowling_id: '22338',
              team_bowling_name: '2nd XI',
              match_id: 5270849,
            },
          ],
        },
        {
          description: {
            club_batting_id: '5276',
            club_batting_name: 'Rayleigh CC',
            club_bowling_id: '4513',
            club_bowling_name: 'Navestock CC',
            declared: false,
            extra_byes: 4,
            extra_leg_byes: 4,
            extra_no_balls: 1,
            extra_penalty_runs: 0,
            extra_wides: 3,
            forfeited_innings: false,
            innings_number: 1,
            match_id: 5270849,
            overs: 26,
            revised_target_overs: 45,
            runs: 215,
            team_batting_id: '22338',
            team_batting_name: '2nd XI',
            team_bowling_id: '204935',
            team_bowling_name: '1st XI',
            total_extras: 12,
            wickets: 2,
          },
          bat: [
            {
              position: 1,
              batsman_name: 'James Ellis',
              batsman_id: '614028',
              how_out: 'not out',
              runs: 112,
              fours: 12,
              sixes: 5,
              balls: 76,
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 2,
              batsman_name: 'Christopher Henderson',
              batsman_id: '5400727',
              how_out: 'ct',
              fielder_name: 'Imran Munir',
              fielder_id: '5064741',
              bowler_name: 'Billy Greaves',
              bowler_id: '3757848',
              runs: 74,
              fours: 14,
              sixes: 1,
              balls: 70,
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 3,
              batsman_name: 'Mark Acraman',
              batsman_id: '4353624',
              how_out: 'ct',
              fielder_name: 'Ryan Scott',
              fielder_id: '3757849',
              bowler_name: 'Billy Greaves',
              bowler_id: '3757848',
              runs: 12,
              fours: 2,
              balls: 10,
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 4,
              batsman_name: 'Sam Harmsworth',
              batsman_id: '5010596',
              how_out: 'not out',
              runs: 5,
              fours: 1,
              balls: 4,
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 5,
              batsman_name: 'Matthew Walker',
              batsman_id: '6188',
              how_out: 'did not bat',
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 6,
              batsman_name: 'Steven Lynch',
              batsman_id: '741512',
              how_out: 'did not bat',
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 7,
              batsman_name: 'Calum Mayfield',
              batsman_id: '5371998',
              how_out: 'did not bat',
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 8,
              batsman_name: 'Aaron Mayfield',
              batsman_id: '4114658',
              how_out: 'did not bat',
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 9,
              batsman_name: 'Mihir Patel',
              batsman_id: '3626541',
              how_out: 'did not bat',
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 10,
              batsman_name: 'Nick Green',
              batsman_id: '977636',
              how_out: 'did not bat',
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              position: 11,
              batsman_name: 'Trevor Nunn',
              batsman_id: '5505062',
              how_out: 'did not bat',
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
          ],
          bowl: [
            {
              bowler_name: 'Tom Mccarthy',
              bowler_id: '3974661',
              overs: 5,
              maidens: 1,
              runs: 39,
              wides: 0,
              wickets: 0,
              no_balls: 0,
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              bowler_name: 'Billy Greaves',
              bowler_id: '3757848',
              overs: 6,
              maidens: 0,
              runs: 48,
              wides: 0,
              wickets: 2,
              no_balls: 0,
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              bowler_name: 'Ryan Scott',
              bowler_id: '3757849',
              overs: 6,
              maidens: 0,
              runs: 70,
              wides: 0,
              wickets: 0,
              no_balls: 0,
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              bowler_name: 'Imran Munir',
              bowler_id: '5064741',
              overs: 6,
              maidens: 1,
              runs: 23,
              wides: 0,
              wickets: 0,
              no_balls: 0,
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              bowler_name: 'Liam Faulkner',
              bowler_id: '3691460',
              overs: 3,
              maidens: 0,
              runs: 27,
              wides: 0,
              wickets: 0,
              no_balls: 0,
              club_id: '5276',
              club_name: 'Rayleigh CC',
              team_id: '22338',
              team_name: '2nd XI',
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
          ],
          fow: [
            {
              runs: 178,
              wickets: 1,
              batsman_out_name: 'Christopher Henderson',
              batsman_out_id: '5400727',
              batsman_in_name: 'James Ellis',
              batsman_in_id: '614028',
              batsman_in_runs: 91,
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
            {
              runs: 199,
              wickets: 2,
              batsman_out_name: 'Mark Acraman',
              batsman_out_id: '4353624',
              batsman_in_name: 'James Ellis',
              batsman_in_id: '614028',
              batsman_in_runs: 102,
              team_batting_id: '22338',
              team_batting_name: '2nd XI',
              club_batting_id: '5276',
              club_batting_name: 'Rayleigh CC',
              club_bowling_id: '4513',
              club_bowling_name: 'Navestock CC',
              team_bowling_id: '204935',
              team_bowling_name: '1st XI',
              match_id: 5270849,
            },
          ],
        },
      ],
      teams: [{
        club_id:'5276',
        club_name:'Rayleigh CC',
        team_id: '22338',
        team_name: '2nd XI',
        match_id: 5270849,
        squad: [
          { position: 1,
            player_name: 'James Ellis',
            player_id: '614028',
            captain: false,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 2,
            player_name: 'Christopher Henderson',
            player_id: '5400727',
            captain: false,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 3,
            player_name: 'Mark Acraman',
            player_id: '4353624',
            captain: false,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 4,
            player_name: 'Sam Harmsworth',
            player_id: '5010596',
            captain: false,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 5,
            player_name: 'Matthew Walker',
            player_id: '6188',
            captain: true,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 6,
            player_name: 'Steven Lynch',
            player_id: '741512',
            captain: false,
            wicket_keeper: true,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 7,
            player_name: 'Calum Mayfield',
            player_id: '5371998',
            captain: false,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 8,
            player_name: 'Aaron Mayfield',
            player_id: '4114658',
            captain: false,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 9,
            player_name: 'Mihir Patel',
            player_id: '3626541',
            captain: false,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 10,
            player_name: 'Nick Green',
            player_id: '977636',
            captain: false,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          },
          {
            position: 11,
            player_name: 'Trevor Nunn',
            player_id: '5505062',
            captain: false,
            wicket_keeper: false,
            club_id:'5276',
            club_name:'Rayleigh CC',
            team_id: '22338',
            team_name: '2nd XI',
            match_id: 5270849
          }
        ]
      },
    {
      club_id: '4513',
      club_name: 'Navestock CC',
      team_id: '204935',
      team_name: '1st XI',
      match_id: 5270849,
      squad:[
        {
          position: 1,
          player_name: 'Jonathan Enderby',
          player_id: '3902682',
          captain: false,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        },
        {
          position: 2,
          player_name: 'Tom Greaves',
          player_id: '2568570',
          captain: false,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        },
        {
          position: 3,
          player_name: 'Kieron Scott',
          player_id: '3789286',
          captain: false,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        },
        {
          position: 4,
          player_name: 'Malcolm Goddard',
          player_id: '4927327',
          captain: false,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        },
        {
          position: 5,
          player_name: 'Liam Faulkner',
          player_id: '3691460',
          captain: false,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        },
        {
          position: 6,
          player_name: 'Matthew Richards',
          player_id: '3755520',
          captain: false,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        },
        {
          position: 7,
          player_name: 'Imran Munir',
          player_id: '5064741',
          captain: false,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        },
        {
          position: 8,
          player_name: 'Tom Mccarthy',
          player_id: '3974661',
          captain: false,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        },
        {
          position: 9,
          player_name: 'Billy Greaves',
          player_id: '3757848',
          captain: true,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        },
        {
          position: 10,
          player_name: 'Ryan Scott',
          player_id: '3757849',
          captain: false,
          wicket_keeper: false,
          club_id: '4513',
          club_name: 'Navestock CC',
          team_id: '204935',
          team_name: '1st XI',
          match_id: 5270849
        }
      ]
    }]
    },
  ];

/**
 * MatchDescription_Data 
 */    
export  const MatchDescription_Data = {
    id: 3986452,
    status: 'New',
    published: 'Yes',
    last_updated: '11/06/2019',
    league_name: 'Mid Essex Cricket League',
    league_id: '16868',
    competition_name: 'Division 3',
    competition_id: '85353',
    competition_type: 'League',
    match_type: 'Limited Overs',
    game_type: 'Standard',
    countdown_cricket: 'no',
    match_id: '3986452',
    match_date: '08/06/2019',
    match_time: '13:00',
    ground_name: 'Navestock C.C. (The Green)',
    ground_id: '6775',
    home_team_name: '1st XI',
    home_team_id: '204935',
    home_club_name: 'Navestock CC',
    home_club_id: '4513',
    away_team_name: '1st XI',
    away_team_id: '138395',
    away_club_name: 'East Hanningfield and Great Burstead CC',
    away_club_id: '10532',
    umpire_1_name: '',
    umpire_1_id: '',
    umpire_2_name: '',
    umpire_2_id: '',
    umpire_3_name: '',
    umpire_3_id: '',
    referee_name: '',
    referee_id: '',
    scorer_1_name: '',
    scorer_1_id: '',
    scorer_2_name: '',
    scorer_2_id: '',
    toss_won_by_team_id: '138395',
    toss: 'East Hanningfield and Great Burstead CC - 1st XI won the toss and elected to field',
    batted_first: '204935',
    no_of_overs: '45',
    balls_per_innings: '',
    no_of_innings: '1',
    no_of_days: '1',
    no_of_players: '',
    no_of_reserves: '',
    result: 'W',
    result_description: 'Navestock CC - 1st XI - Won',
    result_applied_to: '204935',
    match_notes:
      'Liam Faulkner 66, Matt Simmons 4-29, Billy Greaves 3-12, Dan Firth 2-33 (NCC) - Ryan Dziadulewicz 3-23, Pete Morgan 2-42, Steve Hughes 45, Neil Davidson 33 (EHGBCC)</p><br>',
  };


/**
 * Data describing teams in the PlayCricket match details 
 */
export  const Teams_Testdata: team[] = [
    {
      team_name: '2nd XI',
      team_id: '22338',
      club_name: 'Rayleigh CC',
      club_id: '5276',
    },
    {
      team_name: '1st XI',
      team_id: '204935',
      club_name: 'Navestock CC',
      club_id: '4513',
    },
  ];
